[build]  
  command = "npm --prefix sitemapConfiguration run build && cp sitemap.xml ./"
  publish = "."

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[redirects]]
  from = "/sitemap"
  to = "/sitemap.xml"
  status = 200